# Generated by Django 4.0 on 2022-09-19 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0002_project_third_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='primary_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_manager', to='webpage.manager', verbose_name='Primary manager'),
        ),
        migrations.AlterField(
            model_name='project',
            name='secondary_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_manager', to='webpage.manager', verbose_name='secondary manager'),
        ),
        migrations.AlterField(
            model_name='project',
            name='third_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_manager', to='webpage.manager', verbose_name='third manager'),
        ),
    ]
