# Generated by Django 4.0 on 2022-09-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0004_project_executer_company_secondary_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Организации', 'verbose_name_plural': 'Организации'},
        ),
        migrations.AlterModelOptions(
            name='manager',
            options={'verbose_name': 'Менеджеры', 'verbose_name_plural': 'Менеджеры'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проекты', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='executer_company_secondary',
        ),
        migrations.RemoveField(
            model_name='project',
            name='primary_manager',
        ),
        migrations.RemoveField(
            model_name='project',
            name='secondary_manager',
        ),
        migrations.RemoveField(
            model_name='project',
            name='third_manager',
        ),
        migrations.AddField(
            model_name='project',
            name='manager',
            field=models.ManyToManyField(to='webpage.Manager'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contract_id',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='№ договора'),
        ),
        migrations.AlterField(
            model_name='project',
            name='customer',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Сроки исполнения'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='executer_company',
        ),
        migrations.AddField(
            model_name='project',
            name='executer_company',
            field=models.ManyToManyField(to='webpage.Company'),
        ),
        migrations.AlterField(
            model_name='project',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Наименование объекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='work_statement',
            field=models.TextField(blank=True, null=True, verbose_name='Описание работ'),
        ),
    ]
