# Generated by Django 4.0 on 2022-09-22 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0007_alter_category_options_category_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='category',
            new_name='cat',
        ),
    ]
