# Generated by Django 4.0 on 2022-09-22 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0008_rename_category_project_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('CD', 'Завершено'), ('SD', 'Приостановлено'), ('IP', 'В процессе')], default='IP', max_length=2),
        ),
    ]
