# Generated by Django 4.0 on 2022-09-22 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0011_remove_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Завершено', 'Завершено'), ('Приостановлено', 'Приостановлено'), ('В процессе', 'В процессе')], default='В процессе', max_length=100),
        ),
    ]
