# Generated by Django 4.0 on 2022-09-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0012_project_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='fields',
            field=models.ManyToManyField(blank=True, null=True, to='webpage.FieldItem'),
        ),
    ]
