# Generated by Django 4.0 on 2022-09-23 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0013_fielditem_category_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('className', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='fielditem',
            options={'ordering': ['id'], 'verbose_name': 'Поля', 'verbose_name_plural': 'Поля'},
        ),
        migrations.AddField(
            model_name='project',
            name='statusField',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webpage.status'),
        ),
    ]
