# Generated by Django 4.0 on 2022-09-23 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0014_status_alter_fielditem_options_project_statusfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
    ]
