# Generated by Django 4.0 on 2022-09-23 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0015_remove_project_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='statusField',
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webpage.status', verbose_name='Статус'),
        ),
    ]
