# Generated by Django 4.1.1 on 2022-09-29 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0017_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='note',
        ),
        migrations.AddField(
            model_name='note',
            name='project_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='webpage.project'),
        ),
    ]
