# Generated by Django 4.1.1 on 2022-09-30 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0018_remove_project_note_note_project_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='project_id',
        ),
        migrations.AddField(
            model_name='project',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Примечание'),
        ),
    ]
