# Generated by Django 4.1.1 on 2022-09-30 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0019_remove_note_project_id_project_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='note',
            new_name='notice',
        ),
    ]
