# Generated by Django 4.1.1 on 2022-09-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0020_rename_note_project_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='URL'),
        ),
    ]
