# Generated by Django 4.1.1 on 2022-10-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0024_note_project_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='note',
        ),
        migrations.AddField(
            model_name='project',
            name='note',
            field=models.ManyToManyField(blank=True, null=True, to='webpage.note', verbose_name='Поручение'),
        ),
    ]
