# Generated by Django 4.1.1 on 2022-10-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0025_remove_project_note_project_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
