# Generated by Django 4.1.1 on 2022-10-14 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0028_project_work_reasong'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='work_reasong',
            new_name='work_reason',
        ),
    ]
